### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by IgorGanapolsky** [Jonahss/adb-foreach#1]
Hello,
I tried to install **adb-foreach** with npm, but upon running adb-foreach, I get this error:

> npm WARN enoent ENOENT: no such file or directory, open '/Users/igorganapolsky/workspace/experimental/test2/MyApp_Android/distribution/apk-Beta-debug/package.json'
> npm WARN apk-Beta-debug No description
> npm WARN apk-Beta-debug No repository field.
> npm WARN apk-Beta-debug No README data
> npm WARN apk-Beta-debug No license field.

Please advise,
Igor

**Comment by Jonahss** [comment]
Hi,

How are you running it?
I would do `npm install -g adb-foreach`
And then the `adb-foreach` command is now in your path. So you can run `adb-foreach get-state` or other commands.

**Comment by IgorGanapolsky** [comment]
@Jonahss @changetip $1.  Thank you for this tool.

**Comment by changetip** [comment]
Hi @jonahss, @IgorGanapolsky sent you a tip worth 1,527 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/953714)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by Jonahss** [comment]
wow thanks!
